### PR TITLE
(chore) Add Chinese translations 

### PR DESCRIPTION
**Pull request by jona42-ui**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by denniskigen** [comment]
With the new setup, these should go into the Transifex UI instead.

**Comment by jona42-ui** [comment]
thanks @denniskigen  is it still pending work?

**Comment by denniskigen** [comment]
Not sure, I haven't checked Transifex for a while. This may have already been superseded by ongoing work on Chinese translations. We should probably close the PR and follow things up from the Transifex side.

**Comment by jona42-ui** [comment]
sounds good!

**Comment by denniskigen** [comment]
Closing as discussed above.

**Pull request closed without merging**
